### ISSUE TITLE
Synchronize GitHub Issue templates

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#101]
Follow the example of the new Member/Committer request templates and add templates to ease the process of opening bugs or feature requests.

**Comment by dfarrell07** [comment]
https://github.com/submariner-io/submariner/tree/master/.github/ISSUE_TEMPLATE

**Comment by nyechiel** [comment]
There is some overlap with https://github.com/submariner-io/submariner-website/issues/9 -- let's try to collaborate on this together.

**Comment by dfarrell07** [comment]
Sent to the main submairner-io/submariner repo first, to get feedback and iterate before sending parallel PRs to other repos.

https://github.com/submariner-io/submariner/pull/534/files

**Comment by nyechiel** [comment]
@dfarrell07, with https://github.com/submariner-io/submariner/pull/534 merged, I think it makes sense to follow the same template across the rest of the repos. Wdyt?

**Comment by dfarrell07** [comment]
I haven't done this because I'm not sure if it's something we really want, if folks are happy with the current templates. I've added this to the agenda of the next Automation Sync.

**Comment by dfarrell07** [comment]
Per discussion on the Automation call today, the consensus was that we find these templates helpful and do want to add them to the other repos. I'll work on it. :+1:

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
@nyechiel made [substantial improvements](https://github.com/submariner-io/submariner-operator/commit/3818de0e1363dba4600b9e728732835139ac2796) to the templates in many repos recently. I think the main task here is really to make sure all the templates are present/updated for all the relevant repos.

For example, I see Admiral is quite empty: https://github.com/submariner-io/admiral/tree/devel/.github/ISSUE_TEMPLATE

I think basically we need to copy all the templates from https://github.com/submariner-io/submariner/tree/devel/.github/ISSUE_TEMPLATE to the parallel directores in all repos.

**Comment by nyechiel** [comment]
> @nyechiel made [substantial improvements](https://github.com/submariner-io/submariner-operator/commit/3818de0e1363dba4600b9e728732835139ac2796) to the templates in many repos recently. I think the main task here is really to make sure all the templates are present/updated for all the relevant repos.
> 
> For example, I see Admiral is quite: https://github.com/submariner-io/admiral/tree/devel/.github/ISSUE_TEMPLATE
> 
> I think basically we need to copy all the templates from https://github.com/submariner-io/submariner/tree/devel/.github/ISSUE_TEMPLATE to the parallel directores in all repos.

FWIW, when I pushed the bug template updates, I was thinking that `submariner`, `submariner-operator`, `lighthouse` and `cloud-prepare` are the most important ones. `admiral` is not really user-facing and if I were a user I don't think I would even know what to report there. The same is probably true for `shipyard`. `submariner-charts` is user facing, but specifically for the latest bug template update I decided to skip it because the template itself is really focused on `subctl`. `coastguard` is also quite empty now, but we don't support it at the moment.

**Comment by dfarrell07** [comment]
I guess it's a question of if we want consistent templates for all repos, or if that doesn't really matter as long as we have the important templates for the important repos.

**Comment by nyechiel** [comment]
> I guess it's a question of if we want consistent templates for all repos, or if that doesn't really matter as long as we have the important templates for the important repos.

I think we should strive to be as consistent as possible whenever it makes sense, but not just copy everything from Submariner.

**Comment by dfarrell07** [comment]
Reopening and assigning to @Jaanki per discussions at https://github.com/submariner-io/submariner-operator/pull/1492#issuecomment-883431260.

**Comment by Jaanki** [comment]
Updated bug report template in the following PRs

https://github.com/submariner-io/submariner-operator/pull/1492
https://github.com/submariner-io/cloud-prepare/pull/73
https://github.com/submariner-io/submariner/pull/1502
https://github.com/submariner-io/submariner-charts/pull/162
https://github.com/submariner-io/lighthouse/pull/590

**Comment by Jaanki** [comment]
https://github.com/submariner-io/submariner-operator/pull/1492
