### ISSUE TITLE
Simple diagram for the frontend, as simple as possible

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-website#12]
https://submariner-io.github.io/en/

More details can be given in the architecture section, we want something
simple that will provide an overview of broker + clusters, 

May be even 2 diagrams? (broker-in-cluster, and independent broker?)

**Comment by nyechiel** [comment]
@mangelajo I am wondering if this is still needed given the work on https://github.com/submariner-io/submariner-website/pull/169

**Comment by mangelajo** [comment]
That PR would close this, I'm going to mark it as such. Thanks nir :)
