### ISSUE TITLE
Release Process missing operatorhub.io information

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-website#141]
We should document as part of the Release Process (https://submariner-io.github.io/contributing/release-process/) the steps needed to get an up-to-date image on https://operatorhub.io/operator/submariner so that we always have the latest release available in there.

**Comment by nyechiel** [comment]
I am also wondering if there is a way to get updates automatically appear within OpenShift and operatorhub.io, but let first get the steps documented.

**Comment by mangelajo** [comment]
Why did I close this? :-?

**Comment by nyechiel** [comment]
@SteveMattar what's the latest on this? should we update the docs website with the manual steps needed to update the OpertorHub after each release, or are we close to automating this process?

**Comment by SteveMattar** [comment]
https://github.com/submariner-io/submariner-website/pull/264
