### ISSUE TITLE
Please document the cable-driver options

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-website#162]
@nyechiel suggested: 
As of today, we have three engines available in the codebase: 
strongSwan, Libreswan, and WireGuard. 

strongSwan and Libreswan are both using IPsec as the VPN technology so can be seen as two competing ways to do the same thing. 
Libreswan is the supported and recommended way of setting up IPsec.
WireGuard is not based on IPsec (It's a very new technology)

**Comment by nyechiel** [comment]
The different options are now documented as part of the Gateway Engine page thanks to @skitt : https://submariner-io.github.io/architecture/gateway-engine/
