### ISSUE TITLE
Add documanation about svc.supercluster.local

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-website#167]
Until recently we could access services fqdn (with lighthouse) at: `{service name}.{namespace}.svc.cluster.local`

Since changes https://github.com/submariner-io/submariner-operator/issues/346 and #164, the dns suffix has changed to "svc.supercluster.local".

Please add documentation about supercluster.

**Comment by nyechiel** [comment]
This is being worked on by @aswinsuryan and @vthapar. Please see https://github.com/submariner-io/submariner-website/issues/152

**Comment by manosnoam** [comment]
Hi @nyechiel 
Thanks for adding a link to the fix. 

As we discussed regarding "QE verify workflow" (adding @tfreger) - 
I opened this issue in order to verify the fix, in our case Documantion fix. 
That's why this issue should be left opened until I verified the fix.  

Thanks!

**Comment by manosnoam** [comment]
Closing this issue, as we're now having a new issue to update docs: #202
