### ISSUE TITLE
Document Submariner dependencies

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#174]
As a part of Submariner's CNCF Sandbox proposal, we need to answer these questions:
* List any dependent repos (upstream/downstream) that are required to build the project (including but not limited to libraries, commercial tools, plugins)
* Does the project require any specific versions of projects (or APIs) to interoperate? (e.g. K8s API, CSI, CNI, CRI)?

https://docs.google.com/document/d/173OMp7GgDkK6trUqL1FPNkwRVDD1dTe9Z3-XmIoJhiI

It seems to make sense to create reusable/long-term docs on the Submariner website for this answer, and link to them from the proposal.

**Comment by tpantelis** [comment]
Should we move this to 0.6.0?

**Comment by dfarrell07** [comment]
This is no longer a requirement of the CNCF Sandbox application process.
