### ISSUE TITLE
Document HA fail-over stats 

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-website#196]
Currently, the website does not include any info related to HA. This issue is to include some notes on the time it takes for the datapath to recover when there is a failover of gateway node in the current Active/Passive design for Libreswan Cable Driver.

**Comment by nyechiel** [comment]
@sridhargaddam is there anything else we should document here? IMHO, https://submariner.io/architecture/gateway-engine/ has the required information now.. and we can always improve in the future

**Comment by sridhargaddam** [comment]
> @sridhargaddam is there anything else we should document here? IMHO, https://submariner.io/architecture/gateway-engine/ has the required information now.. and we can always improve in the future

Agree with you @nyechiel . I'll close this issue.
