### ISSUE TITLE
Wesite sub-links of content titles doesn't change current browser address

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-website#201]
Try to press on a content title link like this:

![image](https://user-images.githubusercontent.com/9913945/87946101-44752380-caaa-11ea-9d1e-9f2900066004.png)

It should change the browser address accordingly, but it doesn't...
(it just copy the sub-link to clipboard)

**Comment by nyechiel** [comment]
@manosnoam what do you mean by "should change the browser address accordingly"? Clicking on this icon should give a URL to the specific section you can then paste wherever you want. It should not change anything on the actual page you see.

**Comment by manosnoam** [comment]
See an example here:
https://golang.org/doc/

Each title has a link symbol when pointing it, like:

![image](https://user-images.githubusercontent.com/9913945/87948851-e9453000-caad-11ea-88ee-9a360fc190fc.png)

When clicking on it, the browser is changing to that link, e.g. 
https://golang.org/doc/#wiki

**Comment by dfarrell07** [comment]
@manosnoam I know what you mean, it's not the UX I'm used to from some other websites as well, but I think it makes sense. The icon is a magic link to copy the URL of the section header, but it doesn't actually link to that section. I think the two are mutually exclusive designs, and I think just copying is better than linking and making the user copy from the browser bar.

**Comment by nyechiel** [comment]
Ok, I see what you mean now. The Submbariner website uses the Hugo Leran Theme (https://themes.gohugo.io/hugo-theme-learn/) and that's the way the feature was designed. This is not a bug, but more of feature request. We can probably do some research and find a way to get it done, but I don't think it's a good use of our time given everything else we have going on. @manosnoam is it Ok if we close it for now?

**Comment by manosnoam** [comment]
@dfarrell07 , @nyechiel 
Thanks for the clarification :)
Closing it.
