### ISSUE TITLE
Make sure website is as branding-free as possible

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#206]
While discussing updating the DNS for https://submariner.io/ (original/old Rancher-run site) to point at the upstream website (https://submariner-io.github.io/), it was noted that there is Red Hat branding in the demo videos, which with the current design is very in-your-face from the homepage.

As I understand it, the important part here is cleaning up any obvious branding - I don't think the logos in the video slides themselves are much of an issue (although it's better to use the Submariner logo, as we did with the latest Submariner in 60s video).

Ideas:
1. Remove the videos from the homepage, as they are already linked in the [Online Resources](https://submariner-io.github.io/reading_material/) section.
2. Use text links instead of embedded videos.
3. Edit the video thumbnails to remove the Red Hat logos (take a screenshot of the video, edit out the logo, upload as custom thumbnail).

I proposed 1 in the meeting, but as I look at the website I think it's useful to feature that demo content. I don't love 2 because the embedded-video format works so nicely on mobile. As I think about it more, I think 3 is the best option. That also solves the issue on YouTube, as much as we can reasonably do (without re-making the videos).

What do you think @Oats87, would editing the logos out of the video thumbnails work?

**Comment by dfarrell07** [comment]
We could also link to this Rancher-hosted video? https://www.youtube.com/watch?v=2EL5Md5hszA

**Comment by Oats87** [comment]
I'm still a fan of #1 for now, as I'm not sure that the homepage actually needs specific demo videos. The reality of Submariner is that it's a complex, advanced-skillset required project, and in most cases demos don't manage to fully grasp the full power/capabilities of such styles of project.

**Comment by dfarrell07** [comment]
Cool @Oats87, thanks for the feedback! I'll propose a PR for 1 now.
