### ISSUE TITLE
Document pronunciation of "Submariner"

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#209]
We should document how we say "Submariner", as in "Submarine-er", not the famous Rolex. This was raised in a comment on one of our YouTube videos.

https://www.youtube.com/watch?v=2EL5Md5hszA&lc=Ugz0rw9NJlEHfzWtPP54AaABAg

**Comment by skitt** [comment]
We follow UK pronunciation ;-). (At least according to the dictionaries I checked, both pronunciations are encountered in the US, there’s nothing wrong about our way of saying “Submariner”.)

**Comment by nyechiel** [comment]
@dfarrell07 is it OK if we close this?
