### ISSUE TITLE
no mention of submariner engine pod in the docs here , should be though since its a crucial component...

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/submariner-website#226]
I would excpect it to be explained in : 
https://submariner.io/architecture/

**Comment by pinikomarov** [comment]
so apparently it's synonymous to the deamonSet pod running on the designated gateway node
specified here : https://submariner.io/architecture/gateway-engine/

**Comment by tpantelis** [comment]
It is explained [here](https://submariner.io/architecture/gateway-engine/)
