### ISSUE TITLE
Should sign-offs require real names?

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-website#262]
This was prompted by a recent PR, but the specifics aren’t important.

The Linux kernel, where the DCO originated, requires that [contributors use their real names in their `Signed-off-by` lines](https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin):

> then you just add a line saying:
>
>        Signed-off-by: Random J Developer <random@developer.example.org>
>
> using your real name (sorry, no pseudonyms or anonymous contributions.)

I haven’t found anything relevant in the CNCF on this topic. Should we have a similar requirement? Should we ask legal?

**Comment by dfarrell07** [comment]
That's what Helm seems to require (probably they just copied direction from Linux).

https://github.com/helm/helm/blob/master/CONTRIBUTING.md#sign-your-work

It makes sense, I think we should enforce it. The idea of the DCO is to connect work to a real person who has the right to contribute it, making a record of authentic contributions. It seems like fake names break this, prima facie.

**Comment by skitt** [comment]
An extension to this came up in discussion on the Slack channel: should sign-offs require real email addresses (at least, deliverable email addresses)? This is a pre-existing requirement in the Linux kernel, because patch review is done by email and is typically based on email addresses in commit messages and/or sign-offs, and so it isn’t mentioned there; since our reviews are done on GitHub, we don’t need email addresses for technical purposes, but it seems to me that they are still useful (albeit limited, since for example employer-related email addresses stop working when people change jobs).

**Comment by dfarrell07** [comment]
I think we should enforce both real names and email addresses for sign-offs in code review. It would be great if we could add automation to validate email addresses automatically.

**Comment by skitt** [comment]
I’ll add this to the agenda for an upcoming upstream call.

**Comment by skitt** [comment]
The consensus is that requiring a `Signed-off-by` line is sufficient, without enforcing the validity of its contents. PRs are tied to GitHub accounts anyway.
