### ISSUE TITLE
Create updated SubM project overview presentation recording

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#269]
Create an up-to-date video overview of Submariner. Try to make the content somewhat "timeless", ie talk more about goals and direction than specific technical details of the moment.

This should be uploaded to Submariner's YouTube channel and then submitted as part of Submariner's CNCF Sandbox application process.

Update: Current plan is to use a recording of one or more presentations to CNCF and K8s SIGs.

**Comment by dfarrell07** [comment]
Starting to create script and slides here: https://drive.google.com/drive/folders/1mj1zUNuC6gGP05I294qph7hDS3IGfoBX

**Comment by dfarrell07** [comment]
After iterating on this idea a few times with community members, the current plan is to give updated Submariner talks to K8s SIG MC and CNCF SIG Network, and submit those recordings for our Sandbox application.

**Comment by nyechiel** [comment]
@dfarrell07 should we close this one? FWIW, I am putting together a generic project overview deck. First version should be ready for review next week.

**Comment by dfarrell07** [comment]
@nyechiel I think this is supposed to track getting/submitting the recording of the talk we use those slides for. I'd keep it open, use it to provide details/progress.

**Comment by nyechiel** [comment]
Not a recoding, but we may want to use this slide deck as a baseline: https://docs.google.com/presentation/d/1Z1h4XmqgIER2UnYRvH_CKhKeLXIvTtdg8ywM1yyKsSM/edit?usp=sharing
