### ISSUE TITLE
Subctl guide in-detail

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-website#27]
Provide a detailed cmdline documentation for subctl.

**Comment by dfarrell07** [comment]
@mangelajo want me to work on this one?

**Comment by dfarrell07** [comment]
I think this area is still really dynamic, not ready for detailed docs just yet.

**Comment by nyechiel** [comment]
@mangelajo now that https://submariner-io.github.io/deployment/subctl/ should we close this one? We can always improve it further, but I think it's better to report more specific Issues for this. Wdyt?
