### ISSUE TITLE
Document cleanup steps for Submariner

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-website#272]
This is to document cleanup steps for Submariner:
_Originally posted by @Tarjei400 in https://github.com/submariner-io/submariner-operator/issues/88#issuecomment-647333866_

A real example from our OSP-AWS env:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-Globalnet/46/Test-Report/

Cleanup steps:

### 1 Delete Submariner namespace:
`  $ oc delete namespace submariner-operator`

### 2 Deleting submariner CRDs in the cluster
```
  customresourcedefinition.apiextensions.k8s.io "clusters.submariner.io" deleted
  customresourcedefinition.apiextensions.k8s.io "endpoints.submariner.io" deleted
  customresourcedefinition.apiextensions.k8s.io "gateways.submariner.io" deleted
  customresourcedefinition.apiextensions.k8s.io "multiclusterservices.lighthouse.submariner.io" deleted
  customresourcedefinition.apiextensions.k8s.io "servicediscoveries.submariner.io" deleted
  customresourcedefinition.apiextensions.k8s.io "serviceexports.lighthouse.submariner.io" deleted
  customresourcedefinition.apiextensions.k8s.io "serviceimports.lighthouse.submariner.io" deleted
  customresourcedefinition.apiextensions.k8s.io "submariners.submariner.io" deleted
```

### 3 If you are using vanilla Submariner, please delete the following iptable chains from the nat/filter table of worker nodes
```
  SUBMARINER-INPUT
  SUBMARINER-POSTROUTING
```

### 4 The following chains will have to be deleted - if you are using Globalnet:
```
  SUBMARINER-GN-INGRESS
  SUBMARINER-GN-EGRESS
  SUBMARINER-GN-MARK
```

### 6 Clean Lighthouse ServiceExport DNS list:
```
$ oc apply -f -  <<EOF
  apiVersion: operator.openshift.io/v1
  kind: DNS
  metadata:
    finalizers:
    - dns.operator.openshift.io/dns-controller
    name: default
  spec:
    servers: []
EOF
```

### 7 Remove submariner gateway labels
`$ oc label --all node submariner.io/gateway-`

### 8 Delete the Broker namespace
`$ oc delete namespace submariner-k8s-broker`

**Comment by manosnoam** [comment]
@vthapar , @nyechiel

**Comment by sridhargaddam** [comment]
bump

**Comment by SteveMattar** [comment]
missing `ClusterRoles` and `ClusterRoleBindings`

```
oc delete clusterrole submariner-operator
oc delete clusterrolebinding submariner-operator
oc delete clusterrole submariner-operator-globalnet
oc delete clusterrolebinding submariner-operator-globalnet
```
