### ISSUE TITLE
Explain how to do HA on openshift quickstart

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-website#30]
For example, it should mention the usage of ./prep_for_subm.sh
to open Firewall ports on the public cluster with the broker (e.g AWS).
Currently it only opens ports 500 and 4500, see: 
https://github.com/submariner-io/submariner/issues/240

Then, when running subctl for each submariner member, the join command (or deploy with datalane), must specify those ports with `--ikeport` and `--nattport`

Also, we need to explicitly mention, that having more than 1 node with a gateway label can cause issue as in:
https://github.com/submariner-io/submariner/issues/426

**Comment by mangelajo** [comment]
Thanks @manosnoam very helpful

**Comment by nyechiel** [comment]
@manosnoam I think that the OpenShift quickstart now includes all the information you mentioned. Re: HA, this section was added here: https://submariner.io/architecture/gateway-engine/

Can we close this Issue at this point?

**Comment by manosnoam** [comment]
I don't see "HA" info there...

**Comment by nyechiel** [comment]
@manosnoam please check https://submariner.io/architecture/gateway-engine/ -- it was enhanced with some info on HA and also has a section on "Gateway Failover". There is nothing really specific to OpenShift in the way we do HA, so we wanted to include this info under the architecture section.

**Comment by manosnoam** [comment]
Thanks!
