### ISSUE TITLE
Document everything OVN

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-website#304]
The OVN support will bring some changes that need to be documented from the architecture point of view.

See:  https://github.com/submariner-io/enhancements/pull/11
Related-Issue: https://github.com/submariner-io/submariner/issues/778

**Comment by nyechiel** [comment]
I was discussing this with @sridhargaddam, and wanted to summarize our thinking here:

- At least from a user perspective, OVN should "just work". We do need to:

1. Add OVN to the list of CNI support matrix: https://submariner.io/getting_started/#support-matrix
2. Mention that for OVN-based clusters there is no need to open 4800 UDP ports (which normally being used for vxlan-submariner)
3. Document known issues/limitations (for e.g, OVN is not supported with Globalnet): https://submariner.io/operations/known_issues/ 

- We also need to update some of the architecture pages (and diagrams?), in particular the Route Agent: https://submariner.io/getting_started/architecture/route-agent/

**Comment by sridhargaddam** [comment]
> * Document known issues/limitations (for e.g, OVN is not supported with Globalnet): https://submariner.io/operations/known_issues/

PR raised:
https://github.com/submariner-io/submariner-website/pull/402

**Comment by nyechiel** [comment]
>     * Add OVN to the CNI support matrix: https://submariner.io/getting_started/#support-matrix

PR: https://github.com/submariner-io/submariner-website/pull/403
