### ISSUE TITLE
Service Discovery Architecture uses kubedns instead of CoreDNS

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-website#317]
Service Discovery architecture [page](https://submariner.io/architecture/service-discovery/) uses kubedns instead of CoreDNS. We should change references to CoreDNS.

**Comment by nyechiel** [comment]
In addition to the diagram, we also need to modify the test on this page and replace KubeDNS with CoreDNS.

**Comment by nyechiel** [comment]
@aswinsuryan can you take a look at this?

**Comment by aswinsuryan** [comment]
@nyechiel yes I can.

**Comment by nyechiel** [comment]
@aswinsuryan this PR takes care of the text part: https://github.com/submariner-io/submariner-website/pull/345
You still need to update the diagrams.

**Comment by aswinsuryan** [comment]
> @aswinsuryan this PR takes care of the text part: #345
> You still need to update the diagrams.

ok, thanks for addressing it.
