### ISSUE TITLE
[Docs] [v0.8] Libreswan by default 

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-website#376]
The following need to be updated to reflect that libreswan is now the default driver:

- https://submariner.io/getting_started/architecture/gateway-engine/
- https://submariner.io/operations/deployment/subctl/

**Comment by skitt** [comment]
Libreswan isn’t the default yet!

**Comment by nyechiel** [comment]
> Libreswan isn’t the default yet!

Correct, this was done as a preparation for v0.8-rc. We can merge when the time is right
