### ISSUE TITLE
Website navigation across versions

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-website#428]
Now we have https://submariner.io/0.8/ and https://submariner.io/ , etc.

But once you are in one version there is no way to navigate between versions.

It would be nice to have navigation across versions of the website., For example on the top left have links 
to the same version of the site in a different release, etc, being able to move around.

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
Maybe for now we can just start tagging the website repo, so we have pointers for users to possibly get to older versions.

**Comment by dfarrell07** [comment]
Talking about this on the PR scrub, it seems this isn't really something we want, not worth the work for reward.

**Comment by dfarrell07** [comment]
Talking about this on the PR scrub again, there are some use cases (like when docs differ between versions and we want to link to both), but it also adds a lot of complexity of maintenance and possible bugs.

**Comment by dfarrell07** [comment]
I wonder if we can only do this on some pages, like subctl.

**Comment by dfarrell07** [comment]
We've talked about this many times now, kept it open for a long time. The situation is still the same - it will add overhead, and we're not sure if it's worth it for the one use-case of linking to version-specific SubM docs from ACM's docs.

If we end up with a more pressing need for this we can re-open or open a new issue.
