### ISSUE TITLE
Upload skitt's DevConf 2021 talk to SubM Youtube

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#432]
Upload @skitt's outstanding, demo-heavy Submariner talk to Submariner's Youtube. Link to the [Other Resources](https://submariner.io/other-resources/) website section.

**Comment by skitt** [comment]
Please wait until the talk has been presented at DevConf, I wanted to premiere it there.

**Comment by dfarrell07** [comment]
Ah I didn't realize DevConf hadn't happened yet. Right, makes sense. 👍

**Comment by dfarrell07** [comment]
> Once that’s done, I will upload a non-DevConf-specific edit of the video to our YouTube channel.

DevConf is done, so this is unblocked I think (of course @skitt cycles also pending).

If you make a version without a DevConf intro, maybe we can also use that for Red Hat Summit (https://github.com/submariner-io/submariner/issues/1104)?

**Comment by skitt** [comment]
> > Once that’s done, I will upload a non-DevConf-specific edit of the video to our YouTube channel.
> 
> DevConf is done, so this is unblocked I think (of course @skitt cycles also pending).
> 
> If you make a version without a DevConf intro, maybe we can also use that for Red Hat Summit ([submariner-io/submariner#1104](https://github.com/submariner-io/submariner/issues/1104))?

Yup, when I find some tuits I’ll prepare a version with Submariner branding only for the channel, and another for RHS.

**Comment by nyechiel** [comment]
FWIW, here is the YouTube link for the DevConf talk: https://youtu.be/-HE9iq34Zj8

**Comment by nyechiel** [comment]
I addressed this in this PR https://github.com/submariner-io/submariner-website/pull/502
