### ISSUE TITLE
Use Creative Commons Attribution 4.0 International License for docs

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#438]
Per the CNCF Sandbox application process, documentation should be licensed under the Creative Commons Attribution 4.0 International License.

"All documentation will be received and made available by the CNCF under the Creative Commons Attribution 4.0 International License."

https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy

**Comment by skitt** [comment]
Looking at the git logs, we’ll need relicensing approval from Chris Kim (Rancher), Laura Henning, and Rastislav Szabo (Cisco). All the other contributions are owned by Red Hat.

**Comment by dfarrell07** [comment]
The K8s website migrated from Apache 2.0 to CC BY SA 4.0 here: https://github.com/kubernetes/website/pull/1763

I was hoping to find an example of them getting permissions for relicensing, but I don't see anything along those lines. However, the CNCF legal people seem to have signed off on that PR.

Here's an example where an Eclipse project relicensed (https://github.com/eclipse/omr/pull/1625) and got approvals from contributors (https://github.com/eclipse/omr/issues/1606). They just pinged folks on GitHub as the record of approval to relicense. Do we think that's okay for us? Maybe try to get the non-Red Hat contributors to +1 the PR to change the license?

**Comment by skitt** [comment]
> The K8s website migrated from Apache 2.0 to CC BY SA 4.0 here: [kubernetes/website#1763](https://github.com/kubernetes/website/pull/1763
> 
> I was hoping to find an example of them getting permissions for relicensing, but I don't see anything along those lines. However, the CNCF legal people seem to have signed off on that PR.

Kubernetes contributions require [signing the CNCF CLA](https://github.com/kubernetes/community/blob/master/CLA.md), which allows the CNCF to do this without further agreement.

> Here's an example where an Eclipse project relicensed ([eclipse/omr#1625](https://github.com/eclipse/omr/pull/1625)) and got approvals from contributors ([eclipse/omr#1606](https://github.com/eclipse/omr/issues/1606)). They just pinged folks on GitHub as the record of approval to relicense. Do we think that's okay for us? Maybe try to get the non-Red Hat contributors to +1 the PR to change the license?

We can ask CNCF legal and Red Hat legal to be sure...

**Comment by dfarrell07** [comment]
> We can ask CNCF legal and Red Hat legal to be sure...

I don't see a specific email address for CNCF legal, or a "legal person" on the [staff list](https://www.cncf.io/people/staff/). In the ["Legal Services" docs](https://www.cncf.io/services-for-projects/#legal-services) they say they provide these services but there's no contact info. In the [cncf/artwork repo](https://github.com/cncf/artwork), they say to email info@cncf.io with questions. 

For Red Hat there's a clear internal email we can use.

**Comment by LaumiH** [comment]
If it's enough for me to just say "I consent", then: I consent to the change :)
