### ISSUE TITLE
Use new submariner-operator Helm chart in Helm docs

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#440]
There is a [new Helm chart](https://github.com/submariner-io/submariner-charts/commit/96ff45c2f8ff70490f882d88f7306c45a823520c) that is a loose wrapper around the Operator to deploy Submariner. Move the main Helm docs to use that `submariner-operator` chart, vs the old Helm-only `submariner` chart.

> helm install submariner submariner-latest/submariner

https://submariner.io/operations/deployment/helm/

**Comment by dfarrell07** [comment]
This was reported by a user on Slack.

https://kubernetes.slack.com/archives/C010RJV694M/p1612989666481200

**Comment by asanderson** [comment]
also the following needs to be changed on the https://submariner.io/operations/deployment/helm/ page: `export SUBMARINER_NS=submariner`
