### ISSUE TITLE
Document stable vs devel branches/releases/tags

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#442]
With the effort from @mangelajo and others to enable stable branches, our versions for branches, releases, and tags are a bit more complex. We should clearly document, at least, that:

* `release-<version>` is the latest from that stable branch
* `v<version>` is the release

We may also want to consider renaming the GitHub releases "devel"/"<version>" instead of "Cutting Edge: Devel"/"Cutting Edge: release-<version>" for clarity and consistency.

**Comment by dfarrell07** [comment]
We should also document that we're using this `release-<version>` scheme because it's what K8s/K8s does.

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
I think this is partly covered (although it takes digging) by:

https://submariner.io/development/release-process/#release-versions

and

https://submariner.io/development/release-process/#stable-branches-and-versions

I don't see another good fit elsewhere on the website for documenting this.

We could still consider renaming the releases (basically just using versions instead of extra "Cutting edge" text), but that's personal preference maybe and not worth an issue.
