### ISSUE TITLE
Use twitter-together for community creation of Submariner's Tweets

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#443]
To support curating Submariner's Twitter account by the broader community, use a tool like twitter-together to Tweet by PRs to configuration files.

https://github.com/marketplace/actions/twitter-together

- [x] Set an email for Submariner's Twitter https://twitter.com/settings/email
  - Set to dfarrell@redhat.com for lack of a better option 
- [x] Get a Twitter Developer account
- [x] Generate keys (:heavy_check_mark:) and store in GH Secretes (did with @tpantelis, thanks! :heavy_check_mark:):
  - [x] TWITTER_API_KEY
  - [x] TWITTER_API_SECRET_KEY
  - [x] TWITTER_ACCESS_TOKEN
  - [x] TWITTER_ACCESS_TOKEN_SECRET
- [x] https://github.com/submariner-io/submariner/pull/1623
  - https://github.com/gr2m/twitter-together/blob/master/docs/02-create-twitter-together-workflow.md 
- [x] https://github.com/submariner-io/submariner/pull/1632
- [x] https://github.com/submariner-io/submariner/pull/1633

**Comment by tpantelis** [comment]
bump
