### ISSUE TITLE
Update docs for --components flag replacing --service-discovery

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#448]
```
$ subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1 --service-discovery
Flag --service-discovery has been deprecated, please use --components instead
```

https://submariner.io/operations/deployment/subctl/

Should be updated accordingly.

**Comment by dfarrell07** [comment]
```
src/content/development/shipyard/advanced/_index.en.md:124:  make deploy DEPLOY_ARGS='--deploytool operator --deploytool_broker_args "--service-discovery"'
src/content/development/shipyard/advanced/_index.en.md:145:DEPLOY_ARGS += --deploytool operator --deploytool_broker_args '--service-discovery'
src/content/getting-started/quickstart/openshift/vsphere-aws/_index.md:136:subctl deploy-broker --kubeconfig cluster-b/auth/kubeconfig --service-discovery
src/content/getting-started/quickstart/openshift/globalnet/_index.md:88:subctl deploy-broker  --kubeconfig cluster-a/auth/kubeconfig --service-discovery --globalnet
src/content/getting-started/quickstart/kind/_index.md:86:subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1 --service-discovery
src/content/operations/deployment/subctl/_index.en.md:58:| `--service-discovery`                 | Enable Multi Cluster Service Discovery (default true)
```

**Comment by dfarrell07** [comment]
It's actually more than just the website that needs to be updated, I don't think any use of `--service-discovery` has been migrated to `--components`.

```
[~/go/src/github.com/submariner-io]$ gi '\-\-components'                                                                                                                                                           
submariner-operator/pkg/subctl/cmd/deploybroker.go:65:	_ = deployBroker.PersistentFlags().MarkDeprecated("service-discovery", "please use --components instead")
[~/go/src/github.com/submariner-io]$ gi '\-\-service\-discovery' | grep -v submariner-website                                                                                                                      
submariner-operator/scripts/kind-e2e/e2e.sh:15:[[ ! ${DEPLOY_ARGS} =~ "--service-discovery" ]] || lighthouse=true
submariner-operator/Makefile:29:override DEPLOY_ARGS += --deploytool_broker_args '--service-discovery'
shipyard/scripts/shared/lib/deploy_operator:27:    [[ $service_discovery != true ]] || sd="--service-discovery"
lighthouse/Makefile:19:override DEPLOY_ARGS += --deploytool_broker_args '--service-discovery'
releases/Makefile:9:override DEPLOY_ARGS += $(CLUSTER_SETTINGS_FLAG) --deploytool_broker_args '--service-discovery'
```

**Comment by skitt** [comment]
> It's actually more than just the website that needs to be updated, I don't think any use of `--service-discovery` has been migrated to `--components`.
> 
> ```
> [~/go/src/github.com/submariner-io]$ gi '\-\-components'                                                                                                                                                           
> submariner-operator/pkg/subctl/cmd/deploybroker.go:65:	_ = deployBroker.PersistentFlags().MarkDeprecated("service-discovery", "please use --components instead")
> [~/go/src/github.com/submariner-io]$ gi '\-\-service\-discovery' | grep -v submariner-website                                                                                                                      
> submariner-operator/scripts/kind-e2e/e2e.sh:15:[[ ! ${DEPLOY_ARGS} =~ "--service-discovery" ]] || lighthouse=true
> submariner-operator/Makefile:29:override DEPLOY_ARGS += --deploytool_broker_args '--service-discovery'
> shipyard/scripts/shared/lib/deploy_operator:27:    [[ $service_discovery != true ]] || sd="--service-discovery"
> lighthouse/Makefile:19:override DEPLOY_ARGS += --deploytool_broker_args '--service-discovery'
> releases/Makefile:9:override DEPLOY_ARGS += $(CLUSTER_SETTINGS_FLAG) --deploytool_broker_args '--service-discovery'
> ```

Take care with that though, we need the deployment scripts to continue working with the previous release, so that the upgrade test in `devel` can deploy the previous release.
