### ISSUE TITLE
Update docs with vxlan cable driver support

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner-website#450]
What would you like to be added:
vxlan cable driver details needs to be added in docs
Why is this needed:
As a part of #674 a new vxlan cable driver will be supported. The docs needs to be updated with the appropriate details like configuration, and trouble shooting.

**Comment by tpantelis** [comment]
bump

**Comment by skitt** [comment]
This does have activity, Aswin just added a PR fixing it!
