### ISSUE TITLE
Globalnet 2.0: Update documentation

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-website#455]
Update documentation to capture the latest status of [Globalnet](https://github.com/submariner-io/enhancements/pull/22) implementation.

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
Let's not forget to also remove any references for 169.254.0.0 and change that to 242.254.0.0 as per https://github.com/submariner-io/submariner-operator/pull/1452 /cc @vthapar
