### ISSUE TITLE
Globalnet: How to upgrade from 0.9 to Globalnet 2.0 

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-website#456]
Document how to upgrade from Globalnet Older implementation (aka 0.8 release) to the newer implementation of Globalnet.

**Comment by tpantelis** [comment]
bump

**Comment by sridhargaddam** [comment]
bump

**Comment by nyechiel** [comment]
@sridhargaddam I thought we agreed that this use case is not going to be supported?

**Comment by sridhargaddam** [comment]
> @sridhargaddam I thought we agreed that this use case is not going to be supported?

Yes @nyechiel, we will not support auto-upgrade. The idea is to _"Document how to upgrade from Globalnet Older implementation (aka 0.8 release) to the newer implementation of Globalnet using manual steps"_.
