### ISSUE TITLE
Some top level pages render empty

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-website#462]
this seems like an artifact from hugo or our theme, it makes the site look unfinished / under construction.

- https://submariner.io/operations/
- https://submariner.io/getting-started/quickstart/
- https://submariner.io/getting-started/quickstart/managed-kubernetes/
- https://submariner.io/getting-started/quickstart/openshift/

We could include a TOC on those pages, or, find a way to make hugo not render those and make a link.

**Comment by mangelajo** [comment]
@skitt @dfarrell07  ^ opened here what I was mentioning on slack.

**Comment by dfarrell07** [comment]
ACK, I had this one to track similar: https://github.com/submariner-io/submariner-website/issues/431
