### ISSUE TITLE
Add documentation for the submariner operator use

### ISSUE THREAD

**Issue by MaxBab** [submariner-io/submariner-website#465]
The "Deployment" section of the website mentioning an operator that could be used to deploy submariner.
https://submariner.io/operations/deployment/

The section contains manual configuration, Helm and Calico CNI but missing explanation for the operator.

Could the explanation of operator use and config example be added to the documentation, please?

**Comment by skitt** [comment]
This is still relevant.

**Comment by dfarrell07** [comment]
Talking about this on the PR scrub today, we don't expect users to manually deploy the Operator but to use subctl or Helm or the Bundle. We should update the docs to not recommend the manual method.

**Comment by nyechiel** [comment]
@dfarrell07 are you planning to work on this for 0.12?

**Comment by dfarrell07** [comment]
@nyechiel  Yes, I am hoping to do this before 0.12.
