### ISSUE TITLE
Quickstart guide still shows --service-discovery as part of deploy-broker command

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-website#488]
In the latest release, `--service-discovery` is now replaced with `--components=service-discovery`. The same needs to be updated in the docs.

**Comment by nyechiel** [comment]
@sridhargaddam I think it's a duplicate of https://github.com/submariner-io/submariner-website/issues/477 - let's close one of them

**Comment by sridhargaddam** [comment]
Ohh, was not aware of that @nyechiel. Lets close this one.
