### ISSUE TITLE
Typo in subctl benchmark docs

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-website#595]
In https://submariner.io/operations/deployment/subctl/#benchmark:

- ``subctl benchmark throughput --kubecontexts <context1>[,<context2>] [flags]`` needs to be ``subctl benchmark throughput --kubecontexts <context1>,<context2> [flags]``

- ``subctl benchmark latency --kubecontexts <context1>[,<context2>] [flags]`` needs to be ``subctl benchmark latency --kubecontexts <context1>,<context2> [flags]``

**Comment by dfarrell07** [comment]
The `[,<context2>]` syntax, vs `,<context2>` as you suggest, indicates that the param is optional. I think that's correct in this case, as the next line mentions running within a single cluster:

> The `benchmark latency` command runs a latency benchmark test between two specified clusters or within a single cluster.
