### ISSUE TITLE
Document the complete requirements of the backports script

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-website#607]
At least in some circumstances, `make backport` needs a `GITHUB_TOKEN` with specific access permissions; determine what those circumstances are and document the requirements.

**Comment by dfarrell07** [comment]
@skitt Is this something we want to try to do for 0.12, or can it wait for 0.13?

**Comment by skitt** [comment]
> @skitt Is this something we want to try to do for 0.12, or can it wait for 0.13?

I’ve moved it to the backlog.
