### ISSUE TITLE
Decide on, and document, our Kubernetes support policy

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-website#624]
The release of Kubernetes 1.23 raises the issue of what versions of Kubernetes we test against, in relation to the Kubernetes support matrix. Currently we test against 1.19 through 1.22; https://github.com/submariner-io/shipyard/pull/688 adds support for 1.23 but doesn’t change the tests (except for the “consuming e2e” Shipyard test).

We should document our criteria for our Kubernetes test matrix: do we test only against currently-supported versions, or are there reasons to (a) continue testing against older releases and (b) delay testing against newer releases?

**Comment by Jaanki** [comment]
I think we should support 4 latest versions. So with 1,23 released, it would be 1.20 through 1.23. As per [kubernetes release cadance](https://kubernetes.io/blog/2021/07/20/new-kubernetes-release-cadence/), each year k8s has 3 releases. So somebody starting today (say v1.23) would have a whole year to use Submariner with 1.23 and upgrade to 1.27 (in future) after a year and still have Submariner working. This would avoid need for frequent upgrades.

**Comment by asanderson** [comment]
Currently, it looks like our oldest K8s cluster is v1.19.8.

**Comment by dfarrell07** [comment]
> The Kubernetes project maintains release branches for the most recent three minor releases (1.23, 1.22, 1.21). Kubernetes 1.19 and newer receive approximately 1 year of patch support.

https://kubernetes.io/releases/

Maybe we should parallel the K8s policy, test any versions less than a year old.

@Jaanki's idea might be a simpler way to achieve similar results. There will always be 3 or 4 releases supported, so we can just support the last 4. That would also give users a bit more time to transition.

**Comment by skitt** [comment]
I quite like @Jaanki’s proposal as well, and it fits @asanderson’s usage too.

I am wondering whether we could be more lenient, or rather try to determine what the basic requirements are for “supporting” (or at least testing against) various Kubernetes versions:
* we want to ensure that we test against the latest and greatest, if only to be sure that we don’t depend on objects or methods which are removed (_e.g._ CRD v1beta1, removed in 1.22 — we were ready for this in `subctl` but our charts weren’t);
* we want to at least keep track of any risks attached to the -2/+2 policy, _e.g._ on the clients;
* we want to ensure that we test against the oldest still-supported release, to ensure that we don’t require objects which aren’t available yet.

The availability of objects we need is the main issue to watch out for. The introduction/deprecation/removal rules mean that we always have some time to deal with changes, but they also mean that we can’t support old releases indefinitely without adding code to deal with that (_e.g._ trying to install v1 CRDs and falling back to v1beta1 as an example, although we never actually had to do that). Perhaps that this constraint should be the driver: as long as we don’t _need_ to drop support for a given version, we can leave it in the test matrix.

Right now this would mean that we keep v1.20-v1.23 (those are the current [non-EOL releases](https://kubernetes.io/releases/patch-releases/)), and since v1.19 still works (_and_ has users), we leave that in too. When v1.20 reaches EOL in February, if Submariner `devel` still works with v1.19, we keep v1.19, add v1.24 (probably), and remove v1.20 to keep our test matrix sane — given that all this is driven by the object deprecation cycle, if v1.19 still works, v1.20 will too. When v1.19 stops working, or no longer makes sense, we bump the minimum up to whatever makes sense at that point; this may mean reintroducing v1.20 to the test matrix, or going straight up to v1.21 or v1.22 depending on how far down the road we are.

**Comment by dfarrell07** [comment]
We talked about this on the Submariner dev call today, here's my summary of the take-away TODOs:

- [x] Run all CI against the lastest K8s version by default.
  - [x] https://github.com/submariner-io/submariner-operator/pull/1778
  - [x] https://github.com/submariner-io/shipyard/pull/708
  - [x] https://github.com/submariner-io/submariner-charts/pull/197
  - [x] https://github.com/submariner-io/lighthouse/pull/671
  - [x] https://github.com/submariner-io/submariner-operator/pull/1787
  - [x] https://github.com/submariner-io/submariner-operator/pull/1788
- [x] Run one defaults-only E2E job for each of the currently-supported, non-latest K8s versions.
  - [x] https://github.com/submariner-io/submariner-operator/pull/1778
- [x] Add a GHA workflow that runs all CI for all of the currently-supported, non-latest K8s versions.
  - [x] Add a label to trigger running this workflow against a PR.
  - [x] Run this workflow periodically.
  - [x] Run this workflow on releases.
  - [x] https://github.com/submariner-io/submariner-operator/pull/1791
  - [x] https://github.com/submariner-io/releases/pull/298
- [x] Run one defaults-only E2E job in submariner-operator repo with the oldest K8s version we think works with Submariner.
  - [x] Document that this K8s version should equal the K8s version that subctl refuses to attempt installing Submariner on without force-flag.
  - [x] https://github.com/submariner-io/submariner-operator/pull/1777
  - [x] https://github.com/submariner-io/submariner/pull/1662
- [x] Create user-facing docs summarizing our K8s support.
  - [x] https://github.com/submariner-io/submariner-website/pull/629
- [x] Create dev-facing docs summarizing our CI version policies and how to keep things up-to-date.
  - [x] https://github.com/submariner-io/submariner-website/pull/643
- [x] Add EOL dates to SubM GCal.

**Comment by JeepGuy** [comment]
I didn't get a chance to comment on this before .... I appreciate 1 year of support .. more than that may be a bit too cumbersome. We in the field have to learn to upgrade more regularly than every 2 years or so...

**Comment by dfarrell07** [comment]
I think this is done @skitt (https://github.com/submariner-io/submariner-website/issues/624#issuecomment-992808761).
