### ISSUE TITLE
Document how to upgrade Submariner version 

### ISSUE THREAD

**Issue by josepowera** [submariner-io/submariner-website#625]
Wanted to upgrade version on install using subctl, but can't find any manual regarding how to upgrade version (I find only install manuals)

**Comment by nyechiel** [comment]
@josepowera typically, with subctl, you can obtain the version of subctl you want to upgrade to, and simply re-run the 'join' commands. Agree that we better document this.

**Comment by sridhargaddam** [comment]
Closing this as the associated PRs are now merged.
