### ISSUE TITLE
Document the new --broker-namespace flag

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-website#630]
See https://github.com/submariner-io/submariner-operator/pull/1682 for context

**Comment by donaldh** [comment]
I have added an entry to the deploy-broker flags table. Would you like me to describe the usage in the deployment index as well?

https://github.com/donaldh/submariner-website/tree/broker-namespace

**Comment by nyechiel** [comment]
> I have added an entry to the deploy-broker flags table. Would you like me to describe the usage in the deployment index as well?
> 
> https://github.com/donaldh/submariner-website/tree/broker-namespace

Thanks @donaldh. Yes, I think it makes sense to mention it as part of https://submariner.io/operations/deployment/#deployment-of-the-broker

Also, please note that according to our docs style guide (https://submariner.io/development/website/style-guide/), the term Broker should be capitalized.

**Comment by donaldh** [comment]
Submitted PR #652
