### ISSUE TITLE
Add Performance Benchmarking section

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#631]
Add a section of the website dedicated to `subctl benchmark`, to make it more obvious to users that this is a feature they should use.

We could split the current Monitoring section into Prometheus Metrics and Performance Benchmarking.

**Comment by nyechiel** [comment]
@dfarrell07 are you planning to work on this for 0.12?

**Comment by dfarrell07** [comment]
It's "nice to have" for 0.12, I can try to knock it out tomorrow but it's also okay to move it to the backlog.

**Comment by dfarrell07** [comment]
I'm unassigning myself for now to free this up for someone to maybe-grab on 0.12 Docs Day. I have plenty of docs to think about on the ACM side, help here would be great.

**Comment by dfarrell07** [comment]
We have https://submariner.io/operations/deployment/subctl/#benchmark, which I think covers this. If we want another section that maybe teaches about how to use benchmark to diagnose issues, what to do with the results, that should be a different issue.
