### ISSUE TITLE
Develop guidance getting code review while avoiding a tragedy of the commons

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#663]
We've had a long-running discussion but lack of clarity on Submariner's best practices for requesting code review.

The issue is basically that PR authors want code review faster than Owners are providing it, so frustrated PR authors use tools outside of the normal code review process to get attention (Slack, meetings). This works for the PR authors that explicitly ask for reviews, but leaves the authors who didn't with even fewer Owner cycles for reviews. This pushes more and more PR authors to explicitly ask for reviews, which is likely not as efficient as using the review system correctly and leaves anyone not following this pattern (maybe new folks, maybe shy folks) with very few reviews.

We should discuss this as a community, agree on a solution, and document it in the Code Review Guide.

**Comment by skitt** [comment]
It also leads to PRs simply not being opened, or changes getting lumped together into large PRs which are then difficult to review properly. There are some that get closed by the stale-bot, and there’s little incentive to re-open them at that point since re-opening a PR doesn’t increase its chances of getting reviews.

**Comment by dfarrell07** [comment]
I think it'll be tough to get the dev attention this discussion needs to be successful while we're right before the 0.12 release. Moving this to the backlog, but hoping we can make progress soon.

**Comment by dfarrell07** [comment]
The ad hoc system we're doing now is working decently, let's revisit this if we come up with some good ideas.
