### ISSUE TITLE
Document the new `subctl uninstall` command

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-website#684]
- [x] Document the new uninstall command
- [x] Consider whether we should remove the manual uninstall guide completely (https://submariner.io/operations/cleanup/)  

Depends on https://github.com/submariner-io/submariner-operator/pull/1877

**Comment by nyechiel** [comment]
@dfarrell07 with Tom out on PTO, can you take a look at this one? I want to ensure we have the docs part ready before we do a test day :)

**Comment by sridhargaddam** [comment]
> * [ ]  Consider whether we should remove the manual uninstall guide completely (https://submariner.io/operations/cleanup/)

@nyechiel Currently `subctl uninstall` works by deleting the `submariner` object in the `submariner-operator` namespace and the actual cleanup is done by operator/gateway/globalnet/route-agent pods. If user accidentally deletes the `submariner-operator` namespace instead of using `subctl uninstall`, then these pods will be terminated and we cannot perform proper cleanup in such clusters even if we run `subctl uninstall`. We would get the following error.

```
[sgaddam@localhost submariner]$ subctl uninstall 
? This will completely uninstall Submariner from the cluster. Are you sure you want to continue? Yes
 ✓ Checking if the connectivity component is installed
 ✓ The connectivity component is installed
 ✗ Deleting the Submariner resource - this may take some time 
 ✗ Error deleting Submariner resource "submariner": timed out waiting for the condition
```

The manual steps would help in such cases and also for previous versions of Submariner. 
However, I agree that users SHOULD use the `subctl uninstall` as we now support it.

**Comment by nyechiel** [comment]
> > * [ ]   Consider whether we should remove the manual uninstall guide completely (https://submariner.io/operations/cleanup/)
> 
> @nyechiel Currently `subctl uninstall` works by deleting the `submariner` object in the `submariner-operator` namespace and the actual cleanup is done by operator/gateway/globalnet/route-agent pods. If user accidentally deletes the `submariner-operator` namespace instead of using `subctl uninstall`, then these pods will be terminated and we cannot perform proper cleanup in such clusters even if we run `subctl uninstall`. We would get the following error.
> 
> ```
> [sgaddam@localhost submariner]$ subctl uninstall 
> ? This will completely uninstall Submariner from the cluster. Are you sure you want to continue? Yes
>  ✓ Checking if the connectivity component is installed
>  ✓ The connectivity component is installed
>  ✗ Deleting the Submariner resource - this may take some time 
>  ✗ Error deleting Submariner resource "submariner": timed out waiting for the condition
> ```
> 
> The manual steps would help in such cases and also for previous versions of Submariner. However, I agree that users SHOULD use the `subctl uninstall` as we now support it.

Thanks @sridhargaddam. I trust your judgement. If we choose to keep the manual uninstall steps, I think it makes sense to add a note there that `subctl uninstall` exists starting with 0.12 and recommend using it. While on this, do you know if the manual steps are actually up to date?

**Comment by sridhargaddam** [comment]
> > The manual steps would help in such cases and also for previous versions of Submariner. However, I agree that users SHOULD use the `subctl uninstall` as we now support it.
> 
> Thanks @sridhargaddam. I trust your judgement. If we choose to keep the manual uninstall steps, I think it makes sense to add a note there that `subctl uninstall` exists starting with 0.12 and recommend using it. While on this, do you know if the manual steps are actually up to date?

Actually i was just trying to list possible situations when the manual commands will be necessary even after we support `subctl uninstall ...` command. I'm not suggesting that we retain the manual uninstall steps and it could be confusing too. If we tag the submariner-website (or archive the page), we can point it to users in community who are using older releases and want to know the uninstall steps.

**Comment by nyechiel** [comment]
> > > The manual steps would help in such cases and also for previous versions of Submariner. However, I agree that users SHOULD use the `subctl uninstall` as we now support it.
> > 
> > 
> > Thanks @sridhargaddam. I trust your judgement. If we choose to keep the manual uninstall steps, I think it makes sense to add a note there that `subctl uninstall` exists starting with 0.12 and recommend using it. While on this, do you know if the manual steps are actually up to date?
> 
> Actually i was just trying to list possible situations when the manual commands will be necessary even after we support `subctl uninstall ...` command. I'm not suggesting that we retain the manual uninstall steps and it could be confusing too. If we tag the submariner-website (or archive the page), we can point it to users in community who are using older releases and want to know the uninstall steps.

I have submitted https://github.com/submariner-io/submariner-website/pull/697
