### ISSUE TITLE
 Documentation for deployments and removal using cloud-prepare and subctl for OpenStack

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner-website#702]
Documentation for deployments and removal using cloud-prepare and subctl for Openstack

**Comment by nyechiel** [comment]
@aswinsuryan this is about OpenStack, correct? The little is too generic ;)

**Comment by aswinsuryan** [comment]
> @aswinsuryan this is about OpenStack, correct? The little is too generic ;)

oh sorry ,  corrected it , I created the issue from the epic description which did not contain it. :)

**Comment by aswinsuryan** [comment]
Done with - > https://github.com/submariner-io/submariner-website/pull/729
