### ISSUE TITLE
Known issue: on OpenShift, Globalnet metrics do not show up

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-website#703]
There is an [open bug](submariner-io/subctl#73) to track the issue, but in the meantime we need to mention this in the release notes.

**Comment by nyechiel** [comment]
@maayanf24 can you address this please?

**Comment by maayanf24** [comment]
> There is an [open bug](submariner-io/subctl#73) to track the issue, but in the meantime we need to mention this in the release notes.

@nyechiel  should it be documented in the release notes or on the `known issues` page?

**Comment by nyechiel** [comment]
> > There is an [open bug](submariner-io/subctl#73) to track the issue, but in the meantime we need to mention this in the release notes.
> 
> @nyechiel should it be documented in the release notes or on the `known issues` page?

Probably both?
