### ISSUE TITLE
Define and document "experimental" features

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#741]
Better clarify for users which Submariner features are "experimental". This is useful for reducing unnecessary user surprise and providing an overall more clear set of expectations among users and devs.

Also better define the term "experimental" itself.
Also define how features can be added/removed from the experimental matrix.

Ideas for definitions of "experimental":
* Features without active devs who would likely diagnose issues and fix them quickly.
* "The project team accommodates these features in the code repositories, but the SLA for supporting them in cases of bugs or if the feature stops working entirely, is best effort" - @mkolesnik

Features that have been mentioned as potentially "experimental":
* Helm
* WireGuard
* OVNKubernetes (trending less experimental)
* LoadBalancer service mode (trending less experimental)

Ideas for adding/removing features from the experimental matrix:
* Devs petition to adopt features to remove them from the experimental matrix. Anyone petitions to add features to the experimental matrix if they think the feature meets the definition of "experimental".

**Comment by mkolesnik** [comment]
Experimental features are not quite covered in CI, and if they are then such CI is non-blocking for merging PRs.

I see on the website external networks is explicitly documented as "experimental" so it should probably be on the list.

Also how about Calico CNI? We have docs on how to deploy with it, but we're not actively testing it.

Should we also mark some infra support experimental?

- K3s ?
- Rancher ?
- GKE ?

**Comment by nyechiel** [comment]
@dfarrell07 are you planning to work on this? I think we can still do it for 0.13, as docs should not be bound to the rc0 due-date.

**Comment by dfarrell07** [comment]
Yeah this would be a good one to do as 0.13 stabilizes.
