### ISSUE TITLE
Document network interface alias requirement for GKE

### ISSUE THREAD

**Issue by mikenorgate** [submariner-io/submariner-website#747]
In March 2021 GKE removed the IP forwarding option from GKE (https://cloud.google.com/kubernetes-engine/docs/release-notes#March_10_2021) which limits the ability of the nodes to forward packets where the source address isn't one of the nodes internal IPs

https://cloud.google.com/vpc/docs/using-routes#canipforward
```
VM instances can only send packets whose sources are set to match an internal IP address of its interface in the network.
```

This is stopping the gateway node from being able to forward traffic from outside the cluster stopping Submariner from working

The only workaround I have found so far is to add the remote subnets as alias addresses to the gateway node NIC with this command, this is easier when using GlobalNet as there is only one subnet alias to add, when not using GlobalNet all the subnets from other clusters would need to be added

```
gcloud compute instances network-interfaces update <NODE_NAME> --aliases="<CURRENT_ALIAS>;<SUBMARINER_SUBNET>"
```

**Comment by dfarrell07** [comment]
@mikenorgate Sorry we missed this one. Do you happen to know if it's still an issue? @aswinsuryan volunteered to take a look (but he has a lot going on!).

**Comment by mikenorgate** [comment]
@dfarrell07 Yes this is still an issue but my workaround has been stable
