### ISSUE TITLE
Documentation for using subctl cloud prepare on Azure

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner-website#766]
The documentation needs to be added for 

*How to run to subctl cloud prepare on Azure cloud
*How to cleanup using subctl cloud cleanup on Azure cloud

**Comment by nyechiel** [comment]
@aswinsuryan as discussed on Slack, we need a similar one for OpenStack

**Comment by aswinsuryan** [comment]
> @aswinsuryan as discussed on Slack, we need a similar one for OpenStack

 https://github.com/submariner-io/submariner-website/issues/781
