### ISSUE TITLE
Azure documentation points to red hat aws 

### ISSUE THREAD

**Issue by vieenodp** [submariner-io/submariner-website#790]
Hi ,

The azure documentation, 1st point in prerequisites, points to aws. 
https://submariner.io/getting-started/quickstart/openshift/azure/

**Comment by nyechiel** [comment]
Hi @vieenodp - thanks for reporting this issue. Can you please specify in which section the issue is?

**Comment by nyechiel** [comment]
> Hi @vieenodp - thanks for reporting this issue. Can you please specify in which section the issue is?

Sorry, I was looking at the wrong place. I see where the error is now.
