### ISSUE TITLE
Document Submariner vs related technologies

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#792]
We frequently get questions like "Can you explain Submariner vs \<related technology\>". To better answer this question and help others understand Submariner's role in the multicluster ecosystem, we should make a page on the website dedicated to this subject.

Explain how Submariner relates to (at least):

* Istio
* Skupper

**Comment by skitt** [comment]
@nyechiel any progress on this? ;-)

**Comment by aswinayyolath** [comment]
It would be really helpful to have a dedicated page on the website explaining how Submariner compares to Istio and Skupper. This would make it easier to understand Submariner's role in the multicluster ecosystem. It would be great to have this resource available.

**Comment by nyechiel** [comment]
> It would be really helpful to have a dedicated page on the website explaining how Submariner compares to Istio and Skupper. This would make it easier to understand Submariner's role in the multicluster ecosystem. It would be great to have this resource available.

I will draft something and send a PR for others to review and contribute. Other than Skupper and Istio, any other projects you think I should touch on?

**Comment by aswinayyolath** [comment]
Thanks a lot, this would be awesome! Also, I've heard about tools like Linkerd, Consul, and Kuma. I don't know whether it would be possible to add everything, but definitely including Istio, Skupper, and Linkerd would be nice to have. Thanks again!
