### ISSUE TITLE
Document that VxLAN cable-driver is supported only with no NAT deployments.

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-website#799]
When using VxLAN cable-driver with NAT enabled, we can run into issues in certain environments. Currently Submariner supports VxLAN cable-driver in a no-NAT deployments.

As discussed in the [original issue](https://github.com/submariner-io/submariner/issues/1417), lets document this.

**Comment by sridhargaddam** [comment]
CC: @aswinsuryan

**Comment by manosnoam** [comment]
Please also add to the [Docs](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html-single/release_notes/index#submariner-vxlan) that since VxLAN is an encrypted connection, it is not advised to be used within pubic clouds.

**Comment by oafischer** [comment]
> Please also add to the [Docs](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html-single/release_notes/index#submariner-vxlan) that since VxLAN is an encrypted connection, it is not advised to be used within pubic clouds.

@manosnoam This is being added in a PR for a different issue: https://github.com/stolostron/rhacm-docs/pull/4158

**Comment by dfarrell07** [comment]
This is done in the downstream docs but it seems it still needs to be done upstream.

**Comment by dfarrell07** [comment]
Actually we seem to have this upstream:

> In both cases, the expectation is that connected clusters should be directly reachable without NAT.

https://submariner.io/getting-started/architecture/gateway-engine/

Which seems to cover it.
