### ISSUE TITLE
[EPIC] Contributor Developer guide

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-website#8]
Must include:

* How to contribute to the projects 
* How to compile the projects
* How to validate sourcecode format, and how to fix it.
* How to test the projects: E2E and unit
* How to write testing:
   - Differences between unit and E2E

**Comment by dfarrell07** [comment]
@Jaanki want to work on this one with me? I think your recent (outstanding!) demo experience would be relevant/helpful. This seems like quite a few fairly-different tasks to me, maybe we can split it up into chunks between the of us (or more). I'm doing a lot of other work with the deployment and e2e testing logic, so I can definitely drive those areas.

**Comment by Jaanki** [comment]
@dfarrell07 Sure...I can take 1st 3 points.
