### ISSUE TITLE
Document OVN Globalnet support

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-website#830]
Globalnet is now supported with OVN (https://github.com/submariner-io/submariner/issues/383). The following docs should be updated:

- [x] https://submariner.io/getting-started/architecture/networkplugin-syncer/ovn-kubernetes/
- [x] https://submariner.io/operations/known-issues/#globalnet

**Comment by sridhargaddam** [comment]
> Globalnet is now supported with OVN ([submariner-io/submariner#383](https://github.com/submariner-io/submariner/issues/383)). The following docs should be updated:
> 
> * [ ]  https://submariner.io/getting-started/architecture/networkplugin-syncer/ovn-kubernetes/

The Globalnet architecture to support OVN-K is exactly the same as vanilla Submariner deployments. Hence, no changes are required in this page.
