### ISSUE TITLE
Document how to deploy Submariner on Air-gapped clusters

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-website#852]
Submariner now has all the necessary changes merged to support air-gapped clusters. We can have a dedicated page on the website with notes to help users be aware of the changes that would be necessary and the flags to be passed while installing/running various submariner commands.

**Comment by sridhargaddam** [comment]
Capture the list of submariner images that needs to be pre-loaded.

**Comment by skitt** [comment]
It might be worth adding a command to `subctl` to list the images, since it knows about them anyway.

**Comment by sridhargaddam** [comment]
Also document how users can deploy KIND clusters in an air-gapped (simulated) env.

```
make deploy using=air-gap
```

**Comment by dfarrell07** [comment]
Talking with @sridhargaddam, since most of the steps are common between the two deploy paths, we don't seem to need a dedicated page and the using=air-gap docs are sufficient.
