### ISSUE TITLE
Document why subctl join’s --globalnet flag is useful

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-website#853]
Globalnet is configured on the broker, and joining a cluster follows the broker settings. At first glance the `--globalnet` flag no longer seems useful; but since it is relevant for some niche use-cases, those scenarios should be documented.

**Comment by nyechiel** [comment]
@sridhargaddam can keep me honest here, but IIRC this was added based on user's feedback.This is a very niche use-case where in one central/hub cluster we are disabling Globalnet, however all the member clusters that are joined to the hub cluster use Globalnet.

**Comment by mkolesnik** [comment]
AFAIK we don't support mixed deployments of globalnet, e.g. its either the entire clusterset uses it, or doesnt.

**Comment by skitt** [comment]
The flag was introduced by https://github.com/submariner-io/submariner-operator/pull/972

**Comment by sridhargaddam** [comment]
> @sridhargaddam can keep me honest here, but IIRC this was added based on user's feedback.This is a very niche use-case where in one central/hub cluster we are disabling Globalnet, however all the member clusters that are joined to the hub cluster use Globalnet.

Yes that's correct @nyechiel. Although we do not recommend using a mixed deployment, if configured properly this flag allows Submariner to support some niche use-cases like centralised storage which needs access from tenant clusters. We should get some feedback from the team which requested this use-case before deprecating this flag.
