### ISSUE TITLE
Contribution rules (RFEs)

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-website#9]
* What type of change requires an RFE vs an issue
* Template for RFEs
* Create a directory in projects (or a separate repo just for RFEs -as kubernetes does: enhancements-, or just in the website so they are more public-)

etc etc ...

**Comment by mangelajo** [comment]
Ideas: https://opendev.org/openstack/neutron-specs/src/branch/master/specs/template.rst for inspiration

**Comment by nyechiel** [comment]
Also need to look at: https://github.com/kubernetes/enhancements/blob/master/README.md

**Comment by dfarrell07** [comment]
This might be related to https://github.com/submariner-io/submariner-website/issues/101

**Comment by nyechiel** [comment]
TO DO:

- Clarify how we handle "Enhancement Request", i.e a user asking for a feature to be added, versus "Enhancement Proposal" which is more like a spec coming from a developer with implementation plan

- Document the process under https://submariner-io.github.io/contributing/

**Comment by nyechiel** [comment]
I plan to work on this. A quick summary of my thoughts:

1. Use Case 1: “RFE”, someone asking for a missing feature

- A built-in Issue template; should be available across all repos with submariner, lighthouse, submariner-operator, and coastguard being the key ones

- Such a template already exists today for submariner: https://github.com/submariner-io/submariner/blob/master/.github/ISSUE_TEMPLATE/enhancement.md 

- TO DO: review the term and actual content of the template, and adopt across all repos

2. Use Case 2: “spec”, a developer wanting to document their design proposal 

- Need to be used for major features, especially those who impact the user experience, change APIs, and/or present a notable change of behaviour. This is also a good way to ensure we think about testing, docs, and other such items while scoping the feature work

- Miguel has created this repo for this: https://github.com/submariner-io/enhancements 

- TO DO: agree/clarify the term ("enhancement" creates a confusion with Use Case 1 above)
- TO DO: propose a template
- TO DO: document the workflow as part of https://submariner-io.github.io/contributing/

/cc @mangelajo @skitt @dfarrell07

**Comment by mangelajo** [comment]
> I plan to work on this. A quick summary of my thoughts:
> 
> 1. Use Case 1: “RFE”, someone asking for a missing feature
> 
> * A built-in Issue template; should be available across all repos with submariner, lighthouse, submariner-operator, and coastguard being the key ones
> * Such a template already exists today for submariner: https://github.com/submariner-io/submariner/blob/master/.github/ISSUE_TEMPLATE/enhancement.md

Probably this template should include a link to the enhancements repo template (when exists), suggesting that before development that would be necessary.

May be we should call this one rfe.md ? (to avoid the rfe/enhancement repo confusion part)?

> * TO DO: review the term and actual content of the template, and adopt across all repos
> 
> 1. Use Case 2: “spec”, a developer wanting to document their design proposal
> 
> * Need to be used for major features, especially those who impact the user experience, change APIs, and/or present a notable change in behaviour. This is also a good way to ensure we think about testing, docs, and other such items while scoping the feature work
> * Miguel has created this repo for this: https://github.com/submariner-io/enhancements
> * TO DO: agree/clarify the term ("enhancement" creates a confusion with Use Case 1 above)
I think the definition you made "major feature, changes API or behavior" is pretty clear. :+1: 

> * TO DO: propose a template
:+1: 
> * TO DO: document the workflow as part of https://submariner-io.github.io/contributing/
> 
> /cc @mangelajo @skitt @dfarrell07

**Comment by sridhargaddam** [comment]
> > I plan to work on this. A quick summary of my thoughts:
> > 
> > 1. Use Case 1: “RFE”, someone asking for a missing feature
> > 
> > 
> > * A built-in Issue template; should be available across all repos with submariner, lighthouse, submariner-operator, and coastguard being the key ones
> > * Such a template already exists today for submariner: https://github.com/submariner-io/submariner/blob/master/.github/ISSUE_TEMPLATE/enhancement.md
> 
> Probably this template should include a link to the enhancements repo template (when exists), suggesting that before development that would be necessary.
> 
rfe.md makes sense and will avoid confusion. 
I hope not every RFE requires a design/spec in enhancement proposal as some of the RFEs can be minor changes.

> May be we should call this one rfe.md ? (to avoid the rfe/enhancement repo confusion part)?
> 
> > * TO DO: review the term and actual content of the template, and adopt across all repos
> > 
> > 
> > 1. Use Case 2: “spec”, a developer wanting to document their design proposal
> > 
> > 
> > * Need to be used for major features, especially those who impact the user experience, change APIs, and/or present a notable change in behaviour. This is also a good way to ensure we think about testing, docs, and other such items while scoping the feature work
> > * Miguel has created this repo for this: https://github.com/submariner-io/enhancements
> > * TO DO: agree/clarify the term ("enhancement" creates a confusion with Use Case 1 above)
> >   I think the definition you made "major feature, changes API or behavior" is pretty clear. +1
> 
> > * TO DO: propose a template
> >   +1
> > * TO DO: document the workflow as part of https://submariner-io.github.io/contributing/
> > 
> > /cc @mangelajo @skitt @dfarrell07
