### ISSUE TITLE
Remove duplicate flag explanations

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-website#914]
All `subctl` command explanations have their own flag descriptions on the [`subctl`](https://submariner.io/operations/deployment/subctl/) page. `--kubeconfig` and `--context` flags are common and default to all `subctl` commands. Remove these flag mentions as part of each command description and add a common section explaining that these flags apply to all `subctl` commands.

**Comment by skitt** [comment]
The common section already exists: https://submariner.io/operations/deployment/subctl/#common-options
