### ISSUE TITLE
Configure branch protection for release notes branch, allow committers/members to merge PRs

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-website#989]
The new method of pushing release notes to dedicated branches prevents non-owners from merging PRs. I think this can be fixed by adding users/teams to the branch protection configuration.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#restrict-who-can-push-to-matching-branches

We should at least add all committers, probably all members.

**Comment by skitt** [comment]
I’ve removed the relevant branch protection (which only allowed owners to merge).
